Updated to wait for the remote host to come up before doing remote builds
FossilOrigin-Name: 999692e78c531811e39ff1745b6f1d9ac111cc04

diff --git a/build/make-kit-remote b/build/make-kit-remote
--- a/build/make-kit-remote
+++ b/build/make-kit-remote
@@ -6,6 +6,24 @@ shift
 buildid="$(( hostname; id -u; pwd ) | openssl sha1 | sed 's@^.*= *@@')"
 workdir="/tmp/work-kitcreator-${buildid}"
 
+hostUp='0'
+for try in {1..3}; do
+	checkOk="$(timeout 300 ssh -q "${TARGET}" 'echo ok' 2>/dev/null)"
+
+	if [ "${checkOk}" = 'ok' ]; then
+		hostUp='1'
+		break
+	fi
+
+	sleep 10
+done
+
+if [ "${hostUp}" != '1' ]; then
+	echo "Unable to establish a link to the remote system." >&2
+
+	exit 1
+fi
+
 rsync -aq --delete -e ssh . "${TARGET}:${workdir}/" || exit 1
 
 (
