Updated to use FOSSIL_CHANGE as UUID for download, to prevent potential race condition
FossilOrigin-Name: b00d829cca8d353dfe52e1e7e43c170004719b6a

diff --git a/build/test/do-nightly-tests-and-publish b/build/test/do-nightly-tests-and-publish
--- a/build/test/do-nightly-tests-and-publish
+++ b/build/test/do-nightly-tests-and-publish
@@ -18,8 +18,8 @@ export FOSSIL_CHANGE TESTNAME
 
 # Verify sanity
 issane=1
-if [ ! -f "${KITCREATORFOSSIL}" ]; then
-	echo "Missing Kitcreator Fossil Repo: ${KITCREATORFOSSIL}" >&2
+if [ -z "${FOSSIL_CHANGE}" ]; then
+	echo "Unable to determine name of latest revision, likely missing Kitcreator Fossil Repo: ${KITCREATORFOSSIL}" >&2
 
 	issane=0
 fi
@@ -67,7 +67,7 @@ function die () {
 }
 
 # Download latest tarball
-wget -O 'kitcreator-trunk-tip.tar.gz' -o /dev/null 'http://kitcreator.rkeene.org/fossil/tarball/kitcreator-trunk-tip.tar.gz?uuid=trunk'
+wget -O 'kitcreator-trunk-tip.tar.gz' -o /dev/null "http://kitcreator.rkeene.org/fossil/tarball/kitcreator-trunk-tip.tar.gz?uuid=${FOSSIL_CHANGE}"
 
 tar -xf kitcreator-trunk-tip.tar.gz || die 'Tarball Extraction Failed'
 
